export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_LOADER = "SHOW_LOADER";

export const ADD_DATES = "ADD_DATES";
export const CHANGE_DATES = "CHANGE_DATE";
export const FETCHED_DATES = "FETCHED_DATES";
export const REMOVE_DATES = "REMOVE_DATES";

export const ADD_CLIENT = "ADD_CLIENT";
export const CHANGE_CLIENT = "CHANGE_CLIENT";
export const OPEN_CLIENT = "OPEN_CLIENT";
export const CLOUSE_CLIENT = "CLOUSE_CLIENT";
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const REMOVE_CLIENT = "REMOVE_CLIENT";

export const ADD_PROJECT = "ADD_PROJECT";
export const CHANGE_PROJECT = "CHANGE_PROJECT";
export const OPEN_PROJECT = "OPEN_PROJECT";
export const OPEN_CURRENT_PROJECT = "OPEN_CURRENT_PROJECT";
export const CLOUSE_CURRENT_PROJECT = "CLOUSE_CURRENT_PROJECT";
export const CLOUSE_PROJECT = "CLOUSE_PROJECT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";

export const ADD_PAYMENT = "ADD_PAYMENT";
export const OPEN_PAYMENT = "OPEN_PAYMENT";
export const CLOUSE_PAYMENT = "CLOUSE_PAYMENT";
export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const CHANGE_PAYMENT = "CHANGE_PAYMENT";
export const OPEN_NEW_PAYMENT = "OPEN_NEW_PAYMENT";
export const CLOUSE_NEW_PAYMENT = "CLOUSE_NEW_PAYMENT";
export const REMOVE_PAYMENT = "REMOVE_PAYMENT";



export const CHANGE_CREATE = "CHANGE_CREATE";

export const CHANGE_LIST = "CHANGE_LIST";

export const REMOVE_LIST = "REMOVE_LIST";

export const FETCHED_ROUTES = "FETCHED_ROUTES";
export const ADD_ROUTE = "ADD_ROUTE";
export const OPEN_ROUTE = "OPEN_ROUTE";
export const REMOVE_ROUTE = "REMOVE_ROUTE";
export const CHANGE_ROUTE = "CHANGE_ROUTE";

export const OPEN_DENSITY = "OPEN_DENSITY";
export const ADD_DENSITY = "ADD_DENSITY";
export const FETCHED_DENSITIES = "FETCHED_DENSITIES";

export const ADD_USERINFO = "ADD_USERINFO";
export const FETCHED_USERINFO = "FETCHED_USERINFO";
export const CHANGE_INFO = "CHANGE_INFO";
export const CHANGE_USERINFO = "CHANGE_USERINFO";
export const REMOVE_USERINFOS = "REMOVE_USERINFOS";
